[server]
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#044947"
backgroundColor = "#F5F5F1"
secondaryBackgroundColor = "#F9F9F5"
textColor = "#1F1F1D"
borderColor = "#D9D9D9"
font = "Averta, sans-serif"

[[theme.fontFaces]]
family = "Averta"
url = "app/static/fonts/Averta-Regular-normal-400-100.ttf"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "Averta"
url = "app/static/fonts/Averta-Semibold-normal-600-100.ttf"
weight = 600
style = "normal"

[theme.sidebar]
backgroundColor = "#044947"
textColor = "#FFFFFF"

[[theme.fontFaces]]
family = "Balkist"
url = "app/static/fonts/Balkist-normal-400-100.ttf"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "Balkist"
url = "app/static/fonts/Balkist-italic-400-100.ttf"
weight = 400
style = "italic"
